name: Send Create Webhook to Infrastructure

on:
  pull_request:
    types:
      - opened

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR status every minute for 5 minutes
        id: check_pr
        run: |
          for i in {1..4}; do
            pr_status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
                              | jq -r '.state')
            echo "Check #$i: PR status is $pr_status"
            if [ "$pr_status" = "closed" ]; then
              echo "============================================================================="
              echo "PR is closed. Exiting workflow."
              echo "::set-output name=should_exit::true"
              exit 0
            fi
            sleep 30
          done
          echo "::set-output name=should_exit::false"

      - name: Send Webhook to Infrastructure Repository
        if: steps.check_pr.outputs.should_exit != 'true'
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "============================================================================="
          echo "The PR has not closed"

      - name: Send Webhook to Infrastructure Repository
        run: |
          echo "============================================================================="
          echo "add PR comment"
