name: Send Create Webhook to Infrastructure

on:
  pull_request:
    types:
      - opened

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR status every 20 seconds for 2 minutes
        id: check_pr
        run: |
          for i in {1..6}; do
            echo "Making API call to check PR status..."
            pr_status=$(curl -s -H "Authorization: token ${{ secrets.test_PAT }}" \
                              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
                              | jq -r '.state')
            echo "Check #$i: PR status is $pr_status"
            if [ "$pr_status" = "closed" ]; then
              echo "PR is closed. Exiting workflow."
              echo "::set-output name=should_exit::true"
              exit 0
            fi
            sleep 20
          done
          echo "::set-output name=should_exit::false"

      - name: Check if PR is closed and create artifact
        if: steps.check_pr.outputs.should_exit == 'true'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "PR closed early" > pr-${PR_NUMBER}-closed-early.txt
          echo "::set-output name=pr_closed_early::true"

      - name: Upload PR closed early artifact
        if: steps.check_pr.outputs.should_exit == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: pr-${{ github.event.pull_request.number }}-closed-early-artifact
          path: pr-${{ github.event.pull_request.number }}-closed-early.txt

      - name: Send Webhook to Infrastructure Repository
        if: steps.check_pr.outputs.should_exit != 'true'
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "============================================================================="
          echo "The PR is still open, proceeding with webhook."

      - name: Add PR comment
        if: steps.check_pr.outputs.should_exit != 'true'
        run: |
          echo "============================================================================="
          echo "Adding PR comment..."
      #6