name: Send Destroy Webhook to infra-test

on:
  pull_request:
    types:
      - closed
      - synchronize  # Triggered when PR is merged

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Delay job
        run: sleep 60

      - name: Download PR closed early artifact
        id: download_artifact
        uses: actions/download-artifact@v2
        with:
          name: pr-${{ github.event.pull_request.number }}-closed-early-artifact
          path: artifact

      - name: Check if PR was closed early
        id: check_pr_closed_early
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          if [ -f artifact/pr-${PR_NUMBER}-closed-early.txt ]; then
            echo "PR $PR_NUMBER was closed early, exiting workflow."
            echo "::set-output name=should_exit::true"
          else
            echo "PR $PR_NUMBER was not closed early, continuing with workflow."
            echo "::set-output name=should_exit::false"
          fi

      - name: Send Webhook to Infrastructure Repository
        if: steps.check_workflow.outputs.should_exit != 'true'
        run: |
          echo "============================================================================="
          echo "The PR is still open, proceeding with webhook."
